# Generated by Django 4.1 on 2022-08-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phn', models.BigIntegerField()),
                ('medications', models.CharField(max_length=200)),
                ('med_his', models.CharField(max_length=150)),
                ('education', models.CharField(max_length=150)),
                ('answers', models.CharField(max_length=150, null=True)),
                ('results', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
