# Generated by Django 4.1 on 2022-09-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('password', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('education', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('locality', models.CharField(max_length=150)),
                ('marital', models.CharField(max_length=150)),
                ('consent', models.BigIntegerField(default=0)),
                ('date_of_test', models.DateField(null=True)),
                ('results', models.BigIntegerField(null=True)),
                ('time_1', models.BigIntegerField(null=True)),
            ],
        ),
    ]
