# Generated by Django 4.1 on 2022-09-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='auth_token',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
