# Generated by Django 4.1.2 on 2022-10-19 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionaire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='q_7_text',
        ),
    ]
