# Generated by Django 4.1 on 2022-08-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='time',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
