# Generated by Django 4.1.2 on 2022-10-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='test_number',
            field=models.BigIntegerField(default=0),
        ),
    ]
