# Generated by Django 4.1 on 2022-09-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionaire', '0003_user_data_q_1_any_user_data_q_1_lasted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='q_1_time',
            field=models.FloatField(null=True),
        ),
    ]
