# Generated by Django 4.1 on 2022-09-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionaire', '0004_user_data_q_1_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='time_1',
        ),
        migrations.AddField(
            model_name='user_data',
            name='q_2_any_minus',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='q_2_any_plus',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='q_2_lasted',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='q_2_text_minus',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='q_2_text_plus',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='q_2_time',
            field=models.FloatField(null=True),
        ),
    ]
