# Generated by Django 4.1 on 2022-09-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionaire', '0006_remove_user_data_q_2_lasted_user_data_q_1_check_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='q_2_check',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='q_3_any',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='q_3_check',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='q_3_current',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='q_3_lasted',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='q_3_past',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='q_3_time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='q_3_voluntary',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='q_3_weight',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='q_4_any',
            field=models.BooleanField(null=True),
        ),
    ]
