# Generated by Django 4.1 on 2022-10-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionaire', '0010_alter_user_data_auth_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='q_5_any',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='q_5_lasted',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='q_5_notice',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='q_6_check',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='q_6_time',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='q_7_any',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='q_7_care',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='q_7_check',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='q_7_lasted',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='q_7_text',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='q_7_time',
            field=models.FloatField(default=None, null=True),
        ),
    ]
