# Generated by Django 4.1 on 2022-10-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionaire', '0012_user_data_q_8_check_user_data_q_8_concentration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='q_9_check',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='q_9_time',
            field=models.FloatField(default=None, null=True),
        ),
    ]
