# Generated by Django 4.1 on 2022-10-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionaire', '0013_user_data_q_9_check_user_data_q_9_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='q_10_any',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='q_10_check',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='q_10_other',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='q_10_text',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='q_10_time',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='q_11_change',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='q_11_check',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='q_11_drugs',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='q_11_ill',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='q_11_meds',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='q_11_text',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='q_11_time',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='results',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
