# Generated by Django 4.1.2 on 2022-10-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionaire', '0014_user_data_q_10_any_user_data_q_10_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='q_count',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
